name: Monthly CVM Ingest

on:
  schedule:
    - cron: "0 5 1 * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  ingest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore Google Sheets credentials
        run: |
          mkdir -p .secrets
          echo "${{ secrets.GOOGLE_SHEETS_SERVICE_ACCOUNT }}" > .secrets/service-account.json

      - name: Run ingestion (download + CSV + JSON + site)
        run: |
          python -m data_pipeline.run_pipeline ingest --skip-bigquery --config-path config/pipeline.local.yaml
        env:
          SHEETS_SPREADSHEET_ID: ${{ vars.SHEETS_SPREADSHEET_ID }}
          SHEETS_WORKSHEET_NAME: ${{ vars.SHEETS_WORKSHEET_NAME }}
          SHEETS_WORKSHEET_GID: ${{ vars.SHEETS_WORKSHEET_GID }}
          SHEETS_CNPJ_COLUMN: ${{ vars.SHEETS_CNPJ_COLUMN }}
          SHEETS_CREDENTIALS_PATH: .secrets/service-account.json

      - name: Upload CSV artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-csvs
          path: output/

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/site

  deploy:
    needs: ingest
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
